# Generated by Django 5.0.4 on 2024-04-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="usuario",
            table="Usuarios",
        ),
    ]
